### ISSUE TITLE
Binary Tree Visualizer

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/calc_for_everything#528] opened 2023-10-26 23:35 UTC
### Enter calculator name - 
Binary Tree Visualizer

### Describe calculator functionality - 
As the name suggests , the Binary Tree Visualizer takes values in an array one by one as long as the user wants and makes / updates / changes / modifies the Binary tree in real time by adding step by step how the final tree is reached. The rotations which are typically used in self-balancing binary search trees like AVL trees are LL Rotation (Left-Left Rotation) , RR Rotation (Right-Right Rotation) , LR Rotation (Left-Right Rotation) , RL Rotation (Right-Left Rotation) .

Use these rotations wisely by adding one element of the array at a time in order from the beginning to the end.

### Under which category you wish to place it - 
- [x] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [ ] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

**Comment by surajvast1** [comment] 2023-10-27 08:58
Hey I would like to work on this

**Comment by SarthakKeshari** [comment] 2023-10-28 03:40
Hey @surajvast1,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\binaryTreeVisualizer

Issue completion deadline - 30th Oct 10:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by ShivamPatel-24** [comment] 2023-11-25 22:39
Hi @SarthakKeshari, kindly assign this issue to me. I think this would be a challenging and exciting issue to work on.

**Comment by SarthakKeshari** [comment] 2023-11-26 03:18
Hey @ShivamPatel-24,
Assigned.

You may contribute your code under the folder path -
### calc_for_everything\calculators\src\computer_science\binaryTreeVisualizer

Issue completion deadline - 06th Dec 09:00:00 am IST

*NOTE - In case the issue completion deadline is not met, the issue will be assigned to a new participant*

**Comment by SarthakKeshari** [comment] 2023-11-26 03:21
@ShivamPatel-24,
Abiding by the guidelines, kindly do not create PR unless the issue is assigned.

**Comment by ShivamPatel-24** [comment] 2023-11-26 03:54
@SarthakKeshari That makes sense, I will be mindful of that from now on.

**Comment by SarthakKeshari** [comment] 2023-11-26 08:13
Thanks @ShivamPatel-24 for your input. I have made a note of it and will take into consideration while launching the next version of the website.

**Closed by SarthakKeshari** 2023-11-26 08:13 UTC
Labels: question, admin-choice
